# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MP3

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Column(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Column()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsColumn(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Column
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Column
    def Meta(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MP3.ColumnMeta import ColumnMeta
            obj = ColumnMeta()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Column
    def Int64Col(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MP3.Int64Column import Int64Column
            obj = Int64Column()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Column
    def Float64Col(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MP3.Float64Column import Float64Column
            obj = Float64Column()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Column
    def StringCol(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MP3.StringColumn import StringColumn
            obj = StringColumn()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ColumnStart(builder):
    builder.StartObject(4)

def Start(builder):
    ColumnStart(builder)

def ColumnAddMeta(builder, meta):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(meta), 0)

def AddMeta(builder, meta):
    ColumnAddMeta(builder, meta)

def ColumnAddInt64Col(builder, int64Col):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(int64Col), 0)

def AddInt64Col(builder, int64Col):
    ColumnAddInt64Col(builder, int64Col)

def ColumnAddFloat64Col(builder, float64Col):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(float64Col), 0)

def AddFloat64Col(builder, float64Col):
    ColumnAddFloat64Col(builder, float64Col)

def ColumnAddStringCol(builder, stringCol):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(stringCol), 0)

def AddStringCol(builder, stringCol):
    ColumnAddStringCol(builder, stringCol)

def ColumnEnd(builder):
    return builder.EndObject()

def End(builder):
    return ColumnEnd(builder)
